---
- name: Create user to run container
  ansible.builtin.user:
    name: "{{ container_run_as_user }}"
  when: container_run_as_user != "root"

- name: Check if user is lingering
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ container_run_as_user }}"
  register: user_lingering
  when: container_run_as_user != "root"

- name: Enable lingering is needed
  ansible.builtin.command: "loginctl enable-linger {{ container_run_as_user }}"
  when:
    - not user_lingering.stat.exists
    - container_run_as_user != "root"
